### PR TITLE
Selectable methods

### PR DESCRIPTION
**Pull request by deployHuman**
I think the ability to check against GET and other Methods is really nice if you wanna beef up security even more.
So here a added a optional parameter array of which methods we wanna check in this function.

To find there variables from other the post data field, we check Headers and query instead.

### CODE REVIEW

**Comment by t0mmy742** [comment]
GET, HEAD and OPTIONS methods are considered safe and should not be used to perform changing operations, only for reading operations.
Since it is a bad practice, I'm not sure it should be merged.

**Comment by deployHuman** [comment]
> GET, HEAD and OPTIONS methods are considered safe and should not be used to perform changing operations, only for reading operations. Since it is a bad practice, I'm not sure it should be merged.

Safe - yes as it cant change anything, but there still might be information that wants to be protected and only accessed using the correct token, and not by CSR

As this whole script is to make sure , often at least, that its only a logged in person that is viewing and having access to the information.

And i have made it an option, not a requirement.

**Comment by t0mmy742** [comment]
> Safe - yes as it cant change anything, but there still might be information that wants to be protected and only accessed using the correct token, and not by CSR

The same-origin policy of browsers cannot let attackers get response of their requests. CSRF attackers always act blindly.

**Comment by deployHuman** [comment]
i still think its a good-to-have ability where you want to somewhat close of the requests to only local visitors, and not have your api accessed without any set of rules, as now they have to first visit the page to get a token or else every path is open to everyone.

And if not for the GET security part of this, which is optional, there still is the part that makes every method selectable using the parameter

**Comment by t0mmy742** [comment]
I just do not see where it can be useful to select which methods to protect. You always want to protect each unsafe methods, or none.
Maybe we could do the opposite: not checking if method is POST, PUT... but checking if method is not GET, HEAD...

**Comment by deployHuman** [comment]
well im not here to tell how people will use it, i just know everyone have different use cases and there should be options for whatever you are building.

Me personally, made this as i want to protect my api from outside leech usage, not just csr attacks.

Further more, is there something wrong in implementing this ?
It wont be any breaking changes, and it will add more options and security, so why oppose the change ?

**Comment by t0mmy742** [comment]
> well im not here to tell how people will use it, i just know everyone have different use cases and there should be options for whatever you are building.

"Safe" methods are defined by [RFC 7231](https://datatracker.ietf.org/doc/html/rfc7231#section-4.2.1). We should (IMO) not help people build software not following practices (PSR-7 follows RFC 7231).

> Me personally, made this as i want to protect my api from outside leech usage, not just csr attacks.

Maybe that's something wrong here. This middleware is about CSRF. It seems like you are protecting something else.

> Further more, is there something wrong in implementing this ?
> It wont be any breaking changes, and it will add more options and security, so why oppose the change ?

Nothing wrong about implementing something else. However, it does NOT add more security since safe methods are not vulnerable to CSRF (if used well, of course).

About changes of your PR:
* You are adding two functionalities with this PR: methods configurations AND passing token to headers and URI.
*  `$request->getQueryParams()` means you are passing token through URI. You should not pass secret to URI.
* It misses tests 😄

**Comment by l0gicgate** [comment]
I think this should be done at the route level. I would add the middleware on specific routes or route groups. It seems like we're adding logic for a specific use case here.

@akrabat what do you think of this?

**Comment by akrabat** [comment]
CSRF is not authorisation and this feels like we're conflating two different requirements into one piece of middleware. I would suggest using separate middleware to protect resources appropriately. I'm also uncomfortable with implying that we think that GET/HEAD/OPTIONS are valid HTTP verbs for state-changing  operations as they are not to be used for that purpose.

@GETEXSM Thank you for your proposal, we really appreciate that you took the time to present your ideas to the framework. I'm closing this one, but please feel free to propose other changes either as PRs or as issues for discussion.

**Comment by deployHuman** [comment]
thanks for taking the time to review it at least :)

And as you all point out, i will have to accept how the framework works, or just make my own middleware here.
As you can tell i dont work fulltime with coding, but i´m learning and i´m trying to help out on repos.

**Pull request closed without merging**
